name: storage_wrapper
description: A wrapper for shared_preferences and flutter_secure_storage that provides an unified api and a convenient mocking interface.
version: 2.0.0
homepage: https://github.com/magicleon94/local_storage

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.0.0
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
